# Generated by Django 3.0.7 on 2020-07-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
    ]
