# Generated by Django 3.0.7 on 2020-07-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_map_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='description',
            field=models.CharField(default='', max_length=10240),
        ),
    ]
