# Generated by Django 3.0.7 on 2020-06-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='category',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
