# Generated by Django 3.0.7 on 2020-07-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_bookmark_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='file',
            field=models.FileField(max_length=512, upload_to='media'),
        ),
    ]
